const editarPuestoPage = () => {
    return (
        <div className="">
            SE EDITA PUESTO.
            SE PUEDEN EDITAR NOMBRE, DESCRIPCION, HABILIDADES REQUERIDAS, NIVEL DE EXPERIENCIA REQUERIDO, SALARIO OFRECIDO, UBICACION DEL PUESTO, TIPO DE CONTRATO (TIEMPO COMPLETO, MEDIO TIEMPO, CONTRATO TEMPORAL), FECHA DE PUBLICACION DEL PUESTO, FECHA DE CIERRE DE APLICACIONES PARA EL PUESTO.
        </div>
    );
}
 
export default editarPuestoPage;